apiVersion: v1
kind: Service
metadata:
  name: {{ include "kollaudo.fullname" . }}
  labels:
    {{- include "kollaudo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "kollaudo.selectorLabels" . | nindent 4 }}
